from __future__ import annotations

UUD_ARTIFACT_SCHEMA = 5

RECOVERY_CAPABILITIES = {
    "exact_materialized",
    "word_geometry",
    "character_geometry",
    "ownership_transfer",
    "policy_blocked",
    "technically_unrecoverable",
}

RECOVERY_STATUSES = {
    "not_attempted",
    "attempted",
    "materialized",
    "semantically_validated",
    "promoted",
    "failed",
}


ALLOWED_ARTIFACT_ORIGINS = {
    "generated",
    "carried_forward",
    "manual_review_artifact",
    "deprecated",
}


GENERATED_REASON = "rebuilt by the UUD artifact baseline pipeline from source PDFs, corpus specs, and generated grounding artifacts"


def _generated(producer: str, build_stage: str) -> dict:
    return {
        "origin": "generated",
        "origin_reason": GENERATED_REASON,
        "producer": producer,
        "build_stage": build_stage,
    }


UUD_ARTIFACT_ORIGIN_POLICY = {
    "article_amendment_relations.jsonl": _generated("relation_builder", "relation_build"),
    "article_versions.jsonl": {
        "origin": "carried_forward",
        "origin_reason": "source-scoped article version audit retained from the reviewed final artifact set; not regenerated by the current baseline builder",
        "producer": "reviewed_artifact_set",
        "build_stage": "compatibility_or_archive",
    },
    "bbox_registry.jsonl": _generated("bbox_builder", "bbox_build"),
    "chunks.jsonl": _generated("chunk_builder", "chunk_build"),
    "document_metadata.jsonl": _generated("metadata_builder", "metadata_build"),
    "document_relations.jsonl": _generated("relation_builder", "relation_build"),
    "evidence_registry.jsonl": _generated("evidence_builder", "evidence_build"),
    "excluded_records.jsonl": _generated("uud_specs", "validation"),
    "graph_edges.jsonl": _generated("graph_builder", "graph_build"),
    "graph_nodes.jsonl": _generated("graph_builder", "graph_build"),
    "legal_units.jsonl": _generated("legal_unit_builder", "legal_unit_build"),
    "metadata.jsonl": _generated("metadata_builder", "metadata_build"),
    "metadata_graph_edges.jsonl": _generated("metadata_builder", "graph_build"),
    "metadata_grounding.jsonl": _generated("metadata_builder", "metadata_build"),
    "metadata_grounding_registry.jsonl": _generated("metadata_builder", "metadata_build"),
    "pages.jsonl": _generated("pages_builder", "ingestion"),
    "pdf_health_report.json": _generated("pdf_health_builder", "ingestion"),
    "promotion_decisions.jsonl": _generated("promotion_builder", "promotion_audit"),
    "retrieval_units.jsonl": _generated("retrieval_builder", "retrieval_build"),
    "source_conflicts.jsonl": _generated("source_conflict_builder", "validation"),
    "source_documents.jsonl": _generated("source_documents_builder", "source_inventory"),
    "source_integrity.json": {
        "origin": "carried_forward",
        "origin_reason": "source integrity audit retained from the reviewed final artifact set; current builders verify source hashes against it",
        "producer": "source_integrity_audit",
        "build_stage": "compatibility_or_archive",
    },
    "validation_alignment_results.jsonl": {
        "origin": "carried_forward",
        "origin_reason": "alignment audit retained from the reviewed final artifact set; not regenerated by the current baseline builder",
        "producer": "validation_alignment_audit",
        "build_stage": "compatibility_or_archive",
    },
    "validation_exception_review_labels.jsonl": {
        "origin": "manual_review_artifact",
        "origin_reason": "human-reviewed labels documenting accepted validation exceptions",
        "producer": "manual_review",
        "build_stage": "manual_review",
    },
    "validation_exceptions.jsonl": {
        "origin": "manual_review_artifact",
        "origin_reason": "human-reviewed exception records preserved for audit and validation context",
        "producer": "manual_review",
        "build_stage": "manual_review",
    },
    "validation_report.json": _generated("validation_pipeline", "validation"),
    "page_text_spans.jsonl": _generated("text_span_builder", "ingestion"),
    "word_bboxes.jsonl": _generated("word_bbox_builder", "ingestion"),
}
