from __future__ import annotations

from pathlib import Path


FINAL_DIR = Path("data/final/uud")


INSERTED_BAB_SPECS = (
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIA",
        "title": "DEWAN PERWAKILAN DAERAH",
        "page_number": 14,
        "start": "BAB VIIA",
        "end": "Pasal 22C",
        "parent_label": "BAB VII",
        "child_labels": ("Pasal 22C", "Pasal 22D"),
        "trim_targets": ("Pasal 22B",),
        "trim_bab": "BAB VII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIB",
        "title": "PEMILIHAN UMUM",
        "page_number": 15,
        "start": "BAB VIIB",
        "end": "Pasal 22E",
        "parent_label": "BAB VII",
        "child_labels": ("Pasal 22E",),
        "trim_targets": ("Pasal 22D", ("BAB VIIA", "Pasal 22D", "(4)")),
        "trim_bab": "BAB VII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIIA",
        "title": "BADAN PEMERIKSA KEUANGAN",
        "page_number": 16,
        "start": "BAB VIIIA",
        "end": "Pasal 23E",
        "parent_label": "BAB VIII",
        "child_labels": ("Pasal 23E", "Pasal 23F", "Pasal 23G"),
        "trim_targets": ("Pasal 23D",),
        "trim_bab": "BAB VIII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB IXA",
        "title": "WILAYAH NEGARA",
        "page_number": 19,
        "start": "BAB IXA",
        "end": "Pasal 25A",
        "parent_label": "BAB IX",
        "child_labels": ("Pasal 25A",),
        "trim_targets": ("Pasal 25",),
        "trim_bab": "BAB IX",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB XA",
        "title": "HAK ASASI MANUSIA",
        "page_number": 20,
        "start": "BAB XA",
        "end": "Pasal 28A",
        "parent_label": "BAB X",
        "child_labels": ("Pasal 28A", "Pasal 28B", "Pasal 28C", "Pasal 28D", "Pasal 28E", "Pasal 28F", "Pasal 28G", "Pasal 28H", "Pasal 28I", "Pasal 28J"),
        "trim_targets": ("Pasal 28",),
        "trim_bab": "BAB X",
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "label": "BAB IXA",
        "title": "WILAYAH NEGARA",
        "page_number": 3,
        "start": "BAB IXA",
        "end": "Pasal 25E",
        "parent_label": None,
        "child_labels": ("Pasal 25E",),
        "trim_targets": (),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "label": "BAB XA",
        "title": "HAK ASASI MANUSIA",
        "page_number": 4,
        "start": "BAB XA",
        "end": "Pasal 28A",
        "parent_label": "BAB X",
        "child_labels": ("Pasal 28A", "Pasal 28B", "Pasal 28C", "Pasal 28D", "Pasal 28E", "Pasal 28F", "Pasal 28G", "Pasal 28H", "Pasal 28I", "Pasal 28J"),
        "trim_targets": ("Pasal 27",),
        "trim_bab": "BAB X",
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIA",
        "title": "DEWAN PERWAKILAN DAERAH",
        "page_number": 4,
        "start": "BAB VIIA",
        "end": "Pasal 22C",
        "parent_label": None,
        "child_labels": ("Pasal 22C", "Pasal 22D"),
        "trim_targets": ("Pasal 17",),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIB",
        "title": "PEMILIHAN UMUM",
        "page_number": 5,
        "start": "BAB VIIB",
        "end": "Pasal 22E",
        "parent_label": None,
        "child_labels": ("Pasal 22E",),
        "trim_targets": ("Pasal 22D",),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIIA",
        "title": "BADAN PEMERIKSA KEUANGAN",
        "page_number": 6,
        "start": "BAB VIIIA",
        "end": "Pasal 23E",
        "parent_label": None,
        "child_labels": ("Pasal 23E", "Pasal 23F", "Pasal 23G"),
        "trim_targets": (),
        "trim_bab": None,
    },
)
