from __future__ import annotations

from pathlib import Path


FINAL_DIR = Path("data/final/uud")


SOURCE_DOCUMENT_SPECS = (
    {
        "source_document_id": "uud::amendment_1_historical",
        "source_role": "amendment_1_historical",
        "temporal_context": "amendment_1_historical",
        "filename": "UUD45_perubahan1.pdf",
        "path": "data/sources/uud/UUD45_perubahan1.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92284/UUD45_perubahan1.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Mon, 01 Jun 2026 05:34:37 GMT",
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "source_role": "amendment_2_historical",
        "temporal_context": "amendment_2_historical",
        "filename": "UUD45_perubahan2.pdf",
        "path": "data/sources/uud/UUD45_perubahan2.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92285/UUD45_perubahan2.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Sat, 30 May 2026 23:46:02 GMT",
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "source_role": "amendment_3_historical",
        "temporal_context": "amendment_3_historical",
        "filename": "UUD45_perubahan3.pdf",
        "path": "data/sources/uud/UUD45_perubahan3.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92286/UUD45_perubahan3.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Sun, 31 May 2026 02:51:17 GMT",
    },
    {
        "source_document_id": "uud::amendment_4_historical",
        "source_role": "amendment_4_historical",
        "temporal_context": "amendment_4_historical",
        "filename": "UUD45_perubahan4.pdf",
        "path": "data/sources/uud/UUD45_perubahan4.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92287/UUD45_perubahan4.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Mon, 01 Jun 2026 06:23:34 GMT",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "source_role": "current_consolidated",
        "temporal_context": "current_consolidated",
        "filename": "UUD45_SatuNaskah.pdf",
        "path": "data/sources/uud/UUD45_SatuNaskah.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92288/UUD45_SatuNaskah.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Sun, 31 May 2026 03:17:01 GMT",
    },
    {
        "source_document_id": "uud::original_historical",
        "source_role": "original_historical",
        "temporal_context": "original_historical",
        "filename": "UUD45.pdf",
        "path": "data/sources/uud/UUD45.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92283/UUD45.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Mon, 01 Jun 2026 03:17:12 GMT",
    },
)


INSERTED_BAB_SPECS = (
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIA",
        "title": "DEWAN PERWAKILAN DAERAH",
        "page_number": 14,
        "start": "BAB VIIA",
        "end": "Pasal 22C",
        "parent_label": "BAB VII",
        "child_labels": ("Pasal 22C", "Pasal 22D"),
        "trim_targets": ("Pasal 22B",),
        "trim_bab": "BAB VII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIB",
        "title": "PEMILIHAN UMUM",
        "page_number": 15,
        "start": "BAB VIIB",
        "end": "Pasal 22E",
        "parent_label": "BAB VII",
        "child_labels": ("Pasal 22E",),
        "trim_targets": ("Pasal 22D", ("BAB VIIA", "Pasal 22D", "(4)")),
        "trim_bab": "BAB VII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIIA",
        "title": "BADAN PEMERIKSA KEUANGAN",
        "page_number": 16,
        "start": "BAB VIIIA",
        "end": "Pasal 23E",
        "parent_label": "BAB VIII",
        "child_labels": ("Pasal 23E", "Pasal 23F", "Pasal 23G"),
        "trim_targets": ("Pasal 23D",),
        "trim_bab": "BAB VIII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB IXA",
        "title": "WILAYAH NEGARA",
        "page_number": 19,
        "start": "BAB IXA",
        "end": "Pasal 25A",
        "parent_label": "BAB IX",
        "child_labels": ("Pasal 25A",),
        "trim_targets": ("Pasal 25",),
        "trim_bab": "BAB IX",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB XA",
        "title": "HAK ASASI MANUSIA",
        "page_number": 20,
        "start": "BAB XA",
        "end": "Pasal 28A",
        "parent_label": "BAB X",
        "child_labels": ("Pasal 28A", "Pasal 28B", "Pasal 28C", "Pasal 28D", "Pasal 28E", "Pasal 28F", "Pasal 28G", "Pasal 28H", "Pasal 28I", "Pasal 28J"),
        "trim_targets": ("Pasal 28",),
        "trim_bab": "BAB X",
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "label": "BAB IXA",
        "title": "WILAYAH NEGARA",
        "page_number": 3,
        "start": "BAB IXA",
        "end": "Pasal 25E",
        "parent_label": None,
        "child_labels": ("Pasal 25E",),
        "trim_targets": (),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "label": "BAB XA",
        "title": "HAK ASASI MANUSIA",
        "page_number": 4,
        "start": "BAB XA",
        "end": "Pasal 28A",
        "parent_label": "BAB X",
        "child_labels": ("Pasal 28A", "Pasal 28B", "Pasal 28C", "Pasal 28D", "Pasal 28E", "Pasal 28F", "Pasal 28G", "Pasal 28H", "Pasal 28I", "Pasal 28J"),
        "trim_targets": ("Pasal 27",),
        "trim_bab": "BAB X",
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIA",
        "title": "DEWAN PERWAKILAN DAERAH",
        "page_number": 4,
        "start": "BAB VIIA",
        "end": "Pasal 22C",
        "parent_label": None,
        "child_labels": ("Pasal 22C", "Pasal 22D"),
        "trim_targets": ("Pasal 17",),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIB",
        "title": "PEMILIHAN UMUM",
        "page_number": 5,
        "start": "BAB VIIB",
        "end": "Pasal 22E",
        "parent_label": None,
        "child_labels": ("Pasal 22E",),
        "trim_targets": ("Pasal 22D",),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIIA",
        "title": "BADAN PEMERIKSA KEUANGAN",
        "page_number": 6,
        "start": "BAB VIIIA",
        "end": "Pasal 23E",
        "parent_label": None,
        "child_labels": ("Pasal 23E", "Pasal 23F", "Pasal 23G"),
        "trim_targets": (),
        "trim_bab": None,
    },
)
