from __future__ import annotations

from pathlib import Path

from tjipto.corpora.uud.provenance_exceptions import (
    ACCEPTED_NONCANONICAL_SOURCE_CONFLICT_TRACE_ONLY,
    SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
)


FINAL_DIR = Path("data/final/uud")


SOURCE_DOCUMENT_SPECS = (
    {
        "source_document_id": "uud::amendment_1_historical",
        "source_role": "amendment_1_historical",
        "temporal_context": "amendment_1_historical",
        "filename": "UUD45_perubahan1.pdf",
        "path": "data/sources/uud/UUD45_perubahan1.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92284/UUD45_perubahan1.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Mon, 01 Jun 2026 05:34:37 GMT",
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "source_role": "amendment_2_historical",
        "temporal_context": "amendment_2_historical",
        "filename": "UUD45_perubahan2.pdf",
        "path": "data/sources/uud/UUD45_perubahan2.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92285/UUD45_perubahan2.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Sat, 30 May 2026 23:46:02 GMT",
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "source_role": "amendment_3_historical",
        "temporal_context": "amendment_3_historical",
        "filename": "UUD45_perubahan3.pdf",
        "path": "data/sources/uud/UUD45_perubahan3.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92286/UUD45_perubahan3.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Sun, 31 May 2026 02:51:17 GMT",
    },
    {
        "source_document_id": "uud::amendment_4_historical",
        "source_role": "amendment_4_historical",
        "temporal_context": "amendment_4_historical",
        "filename": "UUD45_perubahan4.pdf",
        "path": "data/sources/uud/UUD45_perubahan4.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92287/UUD45_perubahan4.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Mon, 01 Jun 2026 06:23:34 GMT",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "source_role": "current_consolidated",
        "temporal_context": "current_consolidated",
        "filename": "UUD45_SatuNaskah.pdf",
        "path": "data/sources/uud/UUD45_SatuNaskah.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92288/UUD45_SatuNaskah.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Sun, 31 May 2026 03:17:01 GMT",
    },
    {
        "source_document_id": "uud::original_historical",
        "source_role": "original_historical",
        "temporal_context": "original_historical",
        "filename": "UUD45.pdf",
        "path": "data/sources/uud/UUD45.pdf",
        "download_url": "https://peraturan.bpk.go.id/Download/92283/UUD45.pdf",
        "source_page_url": "https://peraturan.bpk.go.id/Details/101646/uud-no--",
        "http_last_modified": "Mon, 01 Jun 2026 03:17:12 GMT",
    },
)


PAGE_SOURCE_ORDER = (
    "uud::current_consolidated",
    "uud::original_historical",
    "uud::amendment_1_historical",
    "uud::amendment_2_historical",
    "uud::amendment_3_historical",
    "uud::amendment_4_historical",
)


PAGE_ID_PREFIXES = {
    "uud::current_consolidated": "page::uud_1945_current_consolidated_text",
    "uud::original_historical": "page::uud_1945_original_text",
    "uud::amendment_1_historical": "page::uud_1945_amendment_1",
    "uud::amendment_2_historical": "page::uud_1945_amendment_2",
    "uud::amendment_3_historical": "page::uud_1945_amendment_3",
    "uud::amendment_4_historical": "page::uud_1945_amendment_4",
}


UUD_LEGAL_UNIT_SOURCE_ORDER = (
    "uud::amendment_1_historical",
    "uud::amendment_2_historical",
    "uud::amendment_3_historical",
    "uud::amendment_4_historical",
    "uud::current_consolidated",
    "uud::original_historical",
)


UUD_LEGAL_UNIT_ID_STARTS = {
    "uud::amendment_1_historical": 379,
    "uud::amendment_2_historical": 401,
    "uud::amendment_3_historical": 480,
    "uud::amendment_4_historical": 567,
    "uud::current_consolidated": 1,
    "uud::original_historical": 268,
}


UUD_CHUNK_ID_STARTS = {
    "uud::amendment_1_historical": 1,
    "uud::amendment_2_historical": 23,
    "uud::amendment_3_historical": 102,
    "uud::amendment_4_historical": 189,
    "uud::current_consolidated": 232,
    "uud::original_historical": 499,
}


UUD_INSERTED_BAB_PREDECESSORS = {
    "BAB VIIA": ("BAB VII",),
    "BAB VIIB": ("BAB VIIA", "BAB VII"),
    "BAB VIIIA": ("BAB VIII",),
    "BAB IXA": ("BAB IX",),
    "BAB XA": ("BAB X",),
}


UUD_LEGAL_GRAPH_EDGE_SCHEMA = {
    "INSERTED_AFTER": {
        "category": "structural_sequence",
        "source": "inserted_structural_unit",
        "target": "predecessor_structural_unit",
        "hierarchy_edge": False,
        "runtime_loadable": False,
        "validation_status": "accepted_structural_sequence",
        "derivation_basis": "structural_order",
        "confidence_policy": "inserted_bab_sibling_sequence_artifact",
    },
    "PRECEDES": {
        "category": "structural_sequence",
        "source": "predecessor_structural_unit",
        "target": "following_structural_unit",
        "hierarchy_edge": False,
        "runtime_loadable": False,
        "validation_status": "accepted_structural_sequence",
        "derivation_basis": "structural_order",
        "confidence_policy": "inserted_bab_sibling_sequence_artifact",
    },
    "FOLLOWS": {
        "category": "structural_sequence",
        "source": "following_structural_unit",
        "target": "predecessor_structural_unit",
        "hierarchy_edge": False,
        "runtime_loadable": False,
        "validation_status": "accepted_structural_sequence",
        "derivation_basis": "structural_order",
        "confidence_policy": "inserted_bab_sibling_sequence_artifact",
    },
}


INSERTED_BAB_SPECS = (
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIA",
        "title": "DEWAN PERWAKILAN DAERAH",
        "page_number": 14,
        "start": "BAB VIIA",
        "end": "Pasal 22C",
        "parent_label": "BAB VII",
        "child_labels": ("Pasal 22C", "Pasal 22D"),
        "trim_targets": ("Pasal 22B",),
        "trim_bab": "BAB VII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIB",
        "title": "PEMILIHAN UMUM",
        "page_number": 15,
        "start": "BAB VIIB",
        "end": "Pasal 22E",
        "parent_label": "BAB VII",
        "child_labels": ("Pasal 22E",),
        "trim_targets": ("Pasal 22D", ("BAB VIIA", "Pasal 22D", "(4)")),
        "trim_bab": "BAB VII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB VIIIA",
        "title": "BADAN PEMERIKSA KEUANGAN",
        "page_number": 16,
        "start": "BAB VIIIA",
        "end": "Pasal 23E",
        "parent_label": "BAB VIII",
        "child_labels": ("Pasal 23E", "Pasal 23F", "Pasal 23G"),
        "trim_targets": ("Pasal 23D",),
        "trim_bab": "BAB VIII",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB IXA",
        "title": "WILAYAH NEGARA",
        "page_number": 19,
        "start": "BAB IXA",
        "end": "Pasal 25A",
        "parent_label": "BAB IX",
        "child_labels": ("Pasal 25A",),
        "trim_targets": ("Pasal 25",),
        "trim_bab": "BAB IX",
    },
    {
        "source_document_id": "uud::current_consolidated",
        "label": "BAB XA",
        "title": "HAK ASASI MANUSIA",
        "page_number": 20,
        "start": "BAB XA",
        "end": "Pasal 28A",
        "parent_label": "BAB X",
        "child_labels": (
            "Pasal 28A",
            "Pasal 28B",
            "Pasal 28C",
            "Pasal 28D",
            "Pasal 28E",
            "Pasal 28F",
            "Pasal 28G",
            "Pasal 28H",
            "Pasal 28I",
            "Pasal 28J",
        ),
        "trim_targets": ("Pasal 28",),
        "trim_bab": "BAB X",
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "label": "BAB IXA",
        "title": "WILAYAH NEGARA",
        "page_number": 3,
        "start": "BAB IXA",
        "end": "Pasal 25E",
        "parent_label": None,
        "child_labels": ("Pasal 25E",),
        "trim_targets": (),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_2_historical",
        "label": "BAB XA",
        "title": "HAK ASASI MANUSIA",
        "page_number": 4,
        "start": "BAB XA",
        "end": "Pasal 28A",
        "parent_label": "BAB X",
        "child_labels": (
            "Pasal 28A",
            "Pasal 28B",
            "Pasal 28C",
            "Pasal 28D",
            "Pasal 28E",
            "Pasal 28F",
            "Pasal 28G",
            "Pasal 28H",
            "Pasal 28I",
            "Pasal 28J",
        ),
        "trim_targets": ("Pasal 27",),
        "trim_bab": "BAB X",
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIA",
        "title": "DEWAN PERWAKILAN DAERAH",
        "page_number": 4,
        "start": "BAB VIIA",
        "end": "Pasal 22C",
        "parent_label": None,
        "child_labels": ("Pasal 22C", "Pasal 22D"),
        "trim_targets": ("Pasal 17",),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIB",
        "title": "PEMILIHAN UMUM",
        "page_number": 5,
        "start": "BAB VIIB",
        "end": "Pasal 22E",
        "parent_label": None,
        "child_labels": ("Pasal 22E",),
        "trim_targets": ("Pasal 22D",),
        "trim_bab": None,
    },
    {
        "source_document_id": "uud::amendment_3_historical",
        "label": "BAB VIIIA",
        "title": "BADAN PEMERIKSA KEUANGAN",
        "page_number": 6,
        "start": "BAB VIIIA",
        "end": "Pasal 23E",
        "parent_label": None,
        "child_labels": ("Pasal 23E", "Pasal 23F", "Pasal 23G"),
        "trim_targets": (),
        "trim_bab": None,
    },
)


SOURCE_CONFLICT_SPECS = (
    {
        "affected_pages": [5, 6],
        "anchor_terms": ["ATURAN TAMBAHAN", "Pasal III"],
        "classification": "source_pdf_contains_pasal_iii_anomaly",
        "corpus_id": "uud",
        "provenance": {"donor_id": "uud_1945_amendment_4_aturan_tambahan_pasal_ii_iii_conflict"},
        "provenance_exception_category": ACCEPTED_NONCANONICAL_SOURCE_CONFLICT_TRACE_ONLY,
        "provenance_review_status": "reviewed",
        "provenance_summary": "source_pdf_contains_pasal_iii_anomaly",
        "final_authority_policy": "Sistem menampilkan provenance sumber ini sebagai jejak audit, bukan kesimpulan hukum final.",
        "query_anchor_terms": ["aturan tambahan", "pasal iii", "pasal ii", "pasal 3"],
        "resolution_decision": {
            "canonical_reference_for_current_uud": "uud_1945_current_consolidated_text_aturan_tambahan_pasal_ii",
            "decision_scope": "pipeline_policy_not_final_legal_authority",
            "downstream_policy": {
                "current_consolidated_uud_may_continue_as_active_candidate": True,
                "historical_amendment_4_typo_scope_may_be_source_typo_reference": True,
                "historical_amendment_4_typo_scope_must_not_be_active_unit_candidate": True,
                "no_final_legal_authority_claim": True,
                "no_legal_grade_verified_claim": True,
                "source_typo_reference_use_policy": "explain_source_discrepancy_only",
            },
            "retain_source_typo_trace": True,
            "reviewer_decision": "amendment_4_pasal_iii_is_source_typographical_anomaly",
        },
        "runtime_loadable": False,
        "source_anomaly_kind": "source_marker_sequence_anomaly",
        "source_conflict_id": "uud_1945_amendment_4_aturan_tambahan_pasal_ii_iii_conflict",
        "source_document_id": "uud::amendment_4_historical",
        "status": ACCEPTED_NONCANONICAL_SOURCE_CONFLICT_TRACE_ONLY,
        "type": "source_marker_sequence_anomaly",
    },
    {
        "affected_pages": [1, 3],
        "anchor_terms": ["Pasal 25E", "Pasal 25A"],
        "classification": "source_article_renumbering_provenance",
        "corpus_id": "uud",
        "provenance": {"donor_id": "uud_1945_amendment_2_pasal_25e_current_pasal_25a_renumbering_conflict"},
        "provenance_summary": "renumbering historis dari Pasal 25E ke rujukan kanonik Pasal 25A",
        "final_authority_policy": "Sistem menampilkannya sebagai historical-to-canonical mapping untuk jejak audit, bukan otoritas hukum final untuk penggunaan saat ini.",
        "query_anchor_terms": ["pasal 25e", "pasal 25a", "25e", "25a"],
        "resolution_decision": {
            "canonical_reference_for_current_uud": "uud_current_consolidated_final_citation_evidence_00401",
            "historical_source_reference": "uud_source_role_historical_final_citation_evidence_00050",
            "decision_scope": "pipeline_trace_not_final_legal_authority",
            "no_final_legal_authority_claim": True,
            "retain_source_text_trace": True,
        },
        "runtime_loadable": False,
        "source_anomaly_kind": "renumbering_provenance",
        "source_mapping_kind": "historical_to_canonical_mapping",
        "source_conflict_id": "uud_1945_amendment_2_pasal_25e_current_pasal_25a_renumbering_conflict",
        "source_document_id": "uud::amendment_2_historical",
        "status": "source_discrepancy_recorded",
        "type": "article_renumbering_provenance",
    },
)


EXCLUDED_RECORD_SPECS = (
    {
        "corpus_id": "uud",
        "excluded_record_id": "uud_unified_excluded_policy::uud_chunk_00005",
        "legacy_chunk_id": "uud_chunk_00005",
        "legacy_record_id": "uud_unified_excluded_policy::uud_chunk_00005",
        "reason": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "runtime_loadable": False,
        "source_role": "amendment_1_historical",
        "status": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "unit_label": "(1)",
    },
    {
        "corpus_id": "uud",
        "excluded_record_id": "uud_unified_excluded_policy::uud_chunk_00022",
        "legacy_chunk_id": "uud_chunk_00022",
        "legacy_record_id": "uud_unified_excluded_policy::uud_chunk_00022",
        "reason": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "runtime_loadable": False,
        "source_role": "amendment_1_historical",
        "status": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "unit_label": "Pasal 21",
    },
    {
        "corpus_id": "uud",
        "excluded_record_id": "uud_unified_excluded_policy::uud_chunk_00097",
        "legacy_chunk_id": "uud_chunk_00097",
        "legacy_record_id": "uud_unified_excluded_policy::uud_chunk_00097",
        "reason": "prior_rejected_text_layer_mismatch_confirmed",
        "runtime_loadable": False,
        "source_role": "amendment_2_historical",
        "status": "rejected_confirmed",
        "unit_label": "(5)",
    },
    {
        "corpus_id": "uud",
        "excluded_record_id": "uud_unified_excluded_policy::uud_chunk_00101",
        "legacy_chunk_id": "uud_chunk_00101",
        "legacy_record_id": "uud_unified_excluded_policy::uud_chunk_00101",
        "reason": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "runtime_loadable": False,
        "source_role": "amendment_2_historical",
        "status": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "unit_label": "Pasal 36C",
    },
    {
        "corpus_id": "uud",
        "excluded_record_id": "uud_unified_excluded_policy::uud_chunk_00143",
        "legacy_chunk_id": "uud_chunk_00143",
        "legacy_record_id": "uud_unified_excluded_policy::uud_chunk_00143",
        "reason": "prior_rejected_text_layer_mismatch_confirmed",
        "runtime_loadable": False,
        "source_role": "amendment_3_historical",
        "status": "rejected_confirmed",
        "unit_label": "(3)",
    },
    {
        "corpus_id": "uud",
        "excluded_record_id": "uud_unified_excluded_policy::uud_chunk_00188",
        "legacy_chunk_id": "uud_chunk_00188",
        "legacy_record_id": "uud_unified_excluded_policy::uud_chunk_00188",
        "reason": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "runtime_loadable": False,
        "source_role": "amendment_3_historical",
        "status": SOURCE_TEXT_ACCEPTED_NONRUNTIME_NO_EVIDENCE_BBOX,
        "unit_label": "(6)",
    },
)


METADATA_BLOCK_SPECS = (
    {
        "source_role": "amendment_1_historical",
        "slug": "instrument_closing_issuance_page_0003",
        "page_number": 3,
        "start_marker": "Perubahan tersebut diputuskan",
    },
    {
        "source_role": "amendment_2_historical",
        "slug": "instrument_closing_issuance_page_0008",
        "page_number": 8,
        "start_marker": "Ditetapkan di Jakarta",
    },
    {
        "source_role": "amendment_3_historical",
        "slug": "instrument_closing_issuance_page_0009",
        "page_number": 9,
        "start_marker": "Ditetapkan di Jakarta",
    },
    {
        "source_role": "amendment_4_historical",
        "slug": "instrument_closing_issuance_page_0006",
        "page_number": 6,
        "start_marker": "Perubahan tersebut diputuskan",
    },
    {
        "source_role": "current_consolidated",
        "slug": "source_publication_page_0001",
        "page_number": 1,
        "institution": "MAJELIS PERMUSYAWARATAN RAKYAT SEKRETARIAT JENDERAL " + "\xad" * 18,
        "title_text": "UNDANG\xadUNDANG DASAR NEGARA REPUBLIK INDONESIA TAHUN 1945 DALAM SATU NASKAH",
    },
)
