from __future__ import annotations


MINIMUM_ARTIFACT_FIELDS: dict[str, tuple[str, ...]] = {
    "bbox_registry": (
        "bbox_id",
        "evidence_id",
        "source_document_id",
        "page_number",
        "x0",
        "y0",
        "x1",
        "y1",
    ),
    "chunks": ("chunk_id", "legal_unit_id", "source_document_id", "evidence_ids", "text_span_ids", "authority_kind", "evidence_exists"),
    "evidence_registry": (
        "evidence_id",
        "legal_unit_id",
        "source_document_id",
        "source_url",
        "page_numbers",
        "bbox_refs",
        "text_span_ids",
        "quoted_text",
        "source_sha256",
        "source_role",
        "status",
        "authority_kind",
        "citable_status",
        "citable",
        "citation_final",
        "citation_finality_reason",
        "exactness",
        "evidence_exists",
        "reason_code",
        "runtime_loadable",
        "evidence_owner_kind",
    ),
    "article_amendment_relations": (
        "relation_id",
        "source_legal_unit_id",
        "target_legal_unit_id",
        "source_role",
        "target_source_role",
        "relation_type",
        "bbox_refs",
        "text_span_ids",
        "target_bbox_refs",
        "support_class",
        "target_precision",
        "authority_kind",
        "citation_final",
        "target_geometry_method",
        "target_geometry_source_ids",
    ),
    "graph_edges": (
        "edge_id",
        "source_id",
        "target_id",
        "relation_type",
    ),
    "graph_nodes": ("node_id", "node_type", "authority_kind", "citable_status", "citable", "citation_final", "citation_finality_reason"),
    "legal_units": (
        "legal_unit_id",
        "source_document_id",
        "text_span_ids",
        "authority_kind",
        "citable_status",
        "citable",
        "citation_final",
        "citation_finality_reason",
        "evidence_exists",
    ),
    "page_text_spans": (
        "text_span_id",
        "source_document_id",
        "page_number",
        "text",
        "classification",
        "legal_force",
        "authority_kind",
        "citable_status",
        "citable",
        "citation_final",
        "highlightable",
        "exactness",
        "evidence_ids",
        "span_bbox_ids",
        "evidence_bbox_ids",
        "context_bbox_ids",
        "reason_code",
        "reason",
    ),
    "pages": ("page_id", "source_document_id", "page_number", "text"),
    "retrieval_units": (
        "retrieval_unit_id",
        "evidence_id",
        "legal_unit_id",
        "chunk_id",
        "authority_kind",
        "citable_status",
        "citable",
        "citation_final",
        "citation_finality_reason",
        "evidence_exists",
        "retrieval_trace",
    ),
    "source_documents": ("source_document_id", "sha256", "path", "source_page_url", "download_url"),
    "word_bboxes": (
        "word_bbox_id",
        "source_document_id",
        "page_number",
        "x0",
        "y0",
        "x1",
        "y1",
        "coordinate_space",
        "coordinate_origin",
        "page_width",
        "page_height",
        "page_rotation",
        "page_box_basis",
        "transform_version",
    ),
}
